export enum FulfillmentType {
  STORE_PICKUP = 'STORE_PICKUP',
  SHIPPING = 'SHIPPING'
}

export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID_PENDING_PREP = 'PAID_PENDING_PREP',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  COMPLETED = 'COMPLETED',
  PAID_PENDING_SHIPMENT = 'PAID_PENDING_SHIPMENT',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  AFTER_SALES = 'AFTER_SALES'
}
